name: Cypress tests

on:
  workflow_dispatch:
    inputs:
      repo_hash:
        description: 'Accessibility Checker Repo Hash'
        required: true

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.6
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      wordpress:
        image: wordpress:latest
        env:
          WORDPRESS_DB_HOST: mysql
          WORDPRESS_DB_USER: wordpress
          WORDPRESS_DB_PASSWORD: password
          WORDPRESS_DB_NAME: wordpress
        ports:
          - 80:80
        options: --name wordpress --health-cmd="curl -f http://127.0.0.1" --health-interval=5s --health-timeout=5s --health-retries=15
        volumes:
          - /tmp/wordpress:/var/www/html
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: wp-cli

      - name: Install WP-CLI in WordPress container
        run: docker exec wordpress bash -c "curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp"

      - name: Set up custom hostname
        run: echo "127.0.0.1 rulecheck.local" | sudo tee -a /etc/hosts

      - name: Install WordPress
        run: |
          wp core install --allow-root --ssh=docker:wordpress --path=/tmp/wordpress --url=rulecheck.local --title=Test --admin_user=rulecheck --admin_password=5arWYMJtJnxTN5xpWjKBNS --admin_email=rulecheck@example.com

      - name: Import posts
        run: wp import data/wordpress-export.xml --allow-root --ssh=docker:wordpress

      - name: Install and activate plugin
        run: |
          wp plugin install accessibility-checker --allow-root --ssh=docker-compose:wordpress --path=/tmp/wordpress
          wp plugin activate accessibility-checker --allow-root --ssh=docker-compose:wordpress --path=/tmp/wordpress

      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          start: npx run cypress
          wait-on: 'http://rulecheck.local'
